package app.layout;

import app.entity.BankAccount;
import java.awt.event.ActionEvent;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class BankFrame extends javax.swing.JFrame {

    public BankFrame() {
        initComponents();
        BankAccount.findAll()
                .stream()
                .forEach(this::addItem);
        trasnferAmountButton.addActionListener(this::transferMoney);
    }

    private void addItem(BankAccount bankAccountItem) {
        fromBankAccountComboBox.addItem(bankAccountItem);
        toAccountComboBox.addItem(bankAccountItem);
    }

    private void transferMoney(ActionEvent event) {
        if (amountTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Unesi neki iznos");
            return;
        }
        BigDecimal amount = new BigDecimal(amountTextField.getText());
        BankAccount fromAccount = (BankAccount) fromBankAccountComboBox.getSelectedItem();
        BankAccount toAccount = (BankAccount) toAccountComboBox.getSelectedItem();
        // 1 0 -1
        if (amount.compareTo(fromAccount.getAmount()) > 0) {
            JOptionPane.showMessageDialog(null, "Nemaš dovoljno sredstava");
            return;
        }
        //AŽuriram BAZU odnosno tabelu u bazi(2 recorda)
        BankAccount.transferMoney(fromAccount, toAccount, amount);
        //REFRES
        amountTextField.setText("");
        fromBankAccountComboBox.removeAllItems();
        toAccountComboBox.removeAllItems();
        BankAccount.findAll().forEach(this::addItem);
        fromBankAccountComboBox.setSelectedItem(fromAccount);
        toAccountComboBox.setSelectedItem(toAccount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fromBankAccountComboBox = new javax.swing.JComboBox<>();
        toAccountComboBox = new javax.swing.JComboBox<>();
        fromBankAccountLabel = new javax.swing.JLabel();
        toBankAccountLabel = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        trasnferAmountButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fromBankAccountLabel.setLabelFor(fromBankAccountComboBox);
        fromBankAccountLabel.setText("From bank account");

        toBankAccountLabel.setText("To bank account");

        amountLabel.setText("Transfer amount");

        trasnferAmountButton.setText("EXECUTE TRANSFER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fromBankAccountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toBankAccountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(trasnferAmountButton, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(amountTextField)
                        .addComponent(fromBankAccountComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toAccountComboBox, 0, 231, Short.MAX_VALUE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromBankAccountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromBankAccountLabel))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toAccountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toBankAccountLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountLabel))
                .addGap(26, 26, 26)
                .addComponent(trasnferAmountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(BankFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        BankFrame bankWindow = new BankFrame();
        SwingUtilities.invokeLater(bankWindow::showWindow);
    }

    private void showWindow() {
        pack();
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JComboBox<app.entity.BankAccount> fromBankAccountComboBox;
    private javax.swing.JLabel fromBankAccountLabel;
    private javax.swing.JComboBox<app.entity.BankAccount> toAccountComboBox;
    private javax.swing.JLabel toBankAccountLabel;
    private javax.swing.JButton trasnferAmountButton;
    // End of variables declaration//GEN-END:variables
}
